# Generated by Django 5.2.8 on 2025-12-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trips",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trips",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trips",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="trips",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ItineraryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=5)),
                ("date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("desc", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("lon", models.CharField(blank=True, max_length=20, null=True)),
                ("lat", models.CharField(blank=True, max_length=20, null=True)),
                ("start_time", models.CharField(blank=True, max_length=10, null=True)),
                ("end_time", models.CharField(blank=True, max_length=10, null=True)),
                ("reminder", models.BooleanField(default=True)),
                (
                    "reminder_time",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trips.trips"
                    ),
                ),
            ],
        ),
    ]
