# Generated by Django 5.2.8 on 2025-12-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trips_description_alter_trips_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryactivity",
            name="photo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trips",
            name="photo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
