# Generated by Django 5.2.8 on 2025-12-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_itineraryactivity_photo_trips_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itineraryactivity",
            name="day",
        ),
    ]
