# Generated by Django 5.2.8 on 2025-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_remove_itineraryactivity_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itineraryactivity",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="itineraryactivity",
            name="end_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="itineraryactivity",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="itineraryactivity",
            name="reminder_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="itineraryactivity",
            name="start_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
