# Generated by Django 5.2.8 on 2025-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_alter_itineraryactivity_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itineraryactivity",
            name="photo",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
