# Generated by Django 5.2.8 on 2025-12-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_alter_itineraryactivity_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itineraryactivity",
            name="photo",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
