# Generated by Django 5.2.8 on 2025-12-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notifications",
            old_name="type",
            new_name="notification_type",
        ),
    ]
