# Generated by Django 5.2.8 on 2025-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="access_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
